title: Math4AI
description: Math4AI site (MSc AI, UvA).
theme: just-the-docs

url: https://FloorEijkelboom.github.io/math_site

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/FloorEijkelboom/math_site

search_enabled: true

mermaid:
  version: "9.1.3"

callouts:
  warning:
    title: Warning
    color: red
