title: Math4AI
description: Math4AI site (MSc AI, UvA).
theme: just-the-docs

url: https://FloorEijkelboom.github.io/math4ai

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/FloorEijkelboom/math4ai/

search_enabled: true

mermaid:
  version: "9.1.3"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red